version: 0.1.{build}
branches:
  only:
  - master
  - dev-IEnumerable
max_jobs: 1
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0'
environment:
  NuGetApiKey:
    secure: bsq7k6KBk+iI9LutJ6wQKuJr3P5qf0sEfgD05BGK31V6DXQYfLWrEk9Dpx2zw+7a
before_build:
- cmd: >-
    nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
    
    nuget restore MvvX.Plugins.LiteDb.sln -verbosity detailed
build:
  verbosity: minimal
on_success:
- ps: '& "nuspec\packageGenerator.ps1"'